# Generated by Django 5.2.5 on 2025-09-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Product',
        ),
    ]
